spring:
  profiles:
    active:
    - DBDataSource
    - inMemoryDB
#    , remote
server:
  baseUrl: http://localhost:8080/
  imageUrl: student/images/
  imageServerDir : C:/bitbucket/images/
---
spring:
  profiles: inMemoryDB
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=- 1;DB_CLOSE_ON_EXIT=FALSE
    tomcat:
      driverClassName: org.h2.Driver
      username: sa
      password:
#server:
#  baseUrl: http://localhost:1000/
---
spring:
  profiles: local
server:
    baseUrl: http://localhost:1000/
#  baseUrl: http://localhost:8080/
#  imageUrl: images/